### ISSUE TITLE
Requisito da disciplina satélite "Desenvolvimento Web 2"

### ISSUE THREAD

**Issue by orlandosaraivajr** [marquesluana/-PI_DSM_FATEC_2SEM2023#1]
Criar um sistema Web em PHP alinhado ao tema central.
Pode ser um cadastro simples, alinhado ao conteúdo visto nos dois projetos anteriores.

**Comment by marquesluana** [comment]
Foi criado um sistema web com cadastro, login, agendamento e avaliação, utilizando o conteúdo visto em aula de php, como integração ao banco via PDO, CRUD, session, orientação a objeto, etc.
